//NOTICE: Hier Icons importieren die verwendet werden. Müssen an 3 stellen hinzugefügt werden!
import {
  octAccessibility,
  octAccessibilityInset,
  octAlert,
  octAlertFill,
  octApps,
  octArchive,
  octArrowBoth,
  octArrowDown,
  octArrowDownLeft,
  octArrowDownRight,
  octArrowLeft,
  octArrowRight,
  octArrowSwitch,
  octArrowUp,
  octArrowUpLeft,
  octQuestion,
} from '@ng-icons/octicons';

export const iconList = [
  'octAccessibility',
  'octAccessibilityInset',
  'octAlert',
  'octAlertFill',
  'octApps',
  'octArchive',
  'octArrowBoth',
  'octArrowDown',
  'octArrowDownLeft',
  'octArrowDownRight',
  'octArrowLeft',
  'octArrowRight',
  'octArrowSwitch',
  'octArrowUp',
  'octArrowUpLeft',
  'octQuestion',
];

export const ngIconsRecord: Record<string, string> = {
  octAccessibility,
  octAccessibilityInset,
  octAlert,
  octAlertFill,
  octApps,
  octArchive,
  octArrowBoth,
  octArrowDown,
  octArrowDownLeft,
  octArrowDownRight,
  octArrowLeft,
  octArrowRight,
  octArrowSwitch,
  octArrowUp,
  octArrowUpLeft,
  octQuestion,
};
